---
title: "Wrangling with Tidyverse"
author: "J.Blondeau"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

All the following question use the sttst_all_sites.xlsx file in the /data directory.


1. Import sttstj_all_sites and inspect the data set.  What is the data structure and the data type of each field?

2. How many samples are in the data set?         

3. How many unique habitat types are there?  What are the names of each habitat?

4. How many sites are there in the "PVMT" habitat type?

5. How many sites are there in the "PVMT" or "AGRF" habitat types?

6. How many sites are there in all the habitat types EXCEPT "PVMT"?

7. Show the first 5 records (rows) of...
    - all sites sampled in "AGRF" or "SCR"
    - only show the "yr_site" and "hab" columns
    
<!-- extra line break -->
<br>

8. What is the northern most site sampled in the "BDRK" habitat?

9. What is the western most site sampled in either "AGRF" or "PTRF" habitat?

10. How many years were surveyed in the data set?

11. What is the eastern most site sample in the "AGRF" habitat in 2004?



